import { type BadgeProps } from 'components/atoms/Badge/types';

export const typeColors: Record<string, string> = {
  ice: '#98D8D8',
  bug: '#A8B820',
  fire: '#F08030',
  rock: '#B8A038',
  dark: '#705848',
  water: '#6890F0',
  grass: '#78C850',
  ghost: '#705898',
  steel: '#B8B8D0',
  fairy: '#EE99AC',
  normal: '#A8A878',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  dragon: '#7038F8',
  psychic: '#F85888',
  electric: '#F8D030',
  fighting: '#C03028',
};

export const typeBadges: Record<string, BadgeProps['color']> = {
  ice: 'sky',
  fire: 'red',
  bug: 'green',
  water: 'blue',
  fairy: 'pink',
  grass: 'green',
  flying: 'blue',
  dragon: 'blue',
  rock: 'neutral',
  dark: 'neutral',
  ghost: 'purple',
  psychic: 'pink',
  fighting: 'red',
  ground: 'yellow',
  steel: 'neutral',
  poison: 'purple',
  normal: 'neutral',
  electric: 'yellow',
};
